export const ErrorCodes = {
  // Reservation Eligibility
  RESTAURANT_CLOSED: "RESTAURANT_CLOSED",
  OUTSIDE_OPENING_HOURS: "OUTSIDE_OPENING_HOURS",
  INVALID_ARRIVAL_INTERVAL: "INVALID_ARRIVAL_INTERVAL",
  MAX_RESERVATION_SIZE_EXCEEDED:
    "MAX_RESERVATION_SIZE_EXCEEDED",
  CAPACITY_EXCEEDED: "CAPACITY_EXCEEDED",
  RESERVATION_SPANS_MULTIPLE_DAYS:
    "RESERVATION_SPANS_MULTIPLE_DAYS",

  // Reservation
  RESERVATION_NOT_FOUND:
    "RESERVATION_NOT_FOUND",
  RESERVATION_NOT_CONFIRMED:
    "RESERVATION_NOT_CONFIRMED",
  MISSING_SEARCH_PARAMETER:
    "MISSING_SEARCH_PARAMETER",
  RESERVATION_NOT_AVAILABLE:
    "RESERVATION_NOT_AVAILABLE",

  // Customer
  CUSTOMER_ALREADY_EXISTS:
    "CUSTOMER_ALREADY_EXISTS",
  CUSTOMER_NOT_FOUND:
    "CUSTOMER_NOT_FOUND",

  // Restaurant
  RESTAURANT_NOT_FOUND:
    "RESTAURANT_NOT_FOUND",

  // Table
  TABLE_NOT_FOUND:
    "TABLE_NOT_FOUND",
};